spring:
  application:
    name: flowery-db-server
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:11234/flowery-write-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      username: admin
      password: password
      uri: mongodb://admin:password@localhost:11235/flowery-read-db?authSource=admin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      access: unrestricted
    prometheus:
      access: unrestricted

server:
  port: 8080
  address: 0.0.0.0 # prometheus setting  - allow external connection

